baseURL = "https://HaiNhat-HUST.github.io/"
languageCode = "vi-vn"
title = "Blog"
theme = "PaperMod"
timeZone = "Asia/Ho_Chi_Minh"


# Cấu hình Theme PaperMod
[params]
    env = "production"
    defaultTheme = "auto"
    disableThemeToggle = false
    ShowReadingTime = true
    ShowShareButtons = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowToc = true
    disableSpecial1stPost = false
    disableScrollToTop = false
    disableInlineCSS = false
    disableHomeIcon = false
    
[params.homeInfoParams]
    Title = "HaiNhat-HUST"
    Content = "Tập hack"

[menu]

    [[menu.main]]
        identifier = "ctf"
        name = "CTF Writeups"
        url = "/ctf/"
        weight = 2

    [[menu.main]]
        identifier = "hackthebox"
        name = "Hackthebox"
        url = "/hackthebox/"
        weight = 3
    
    [[menu.main]]
        identifier = "research"
        name = "Research/Sharing"
        url = "/research/"
        weight = 4

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 5
[outputs]
    home = [ "HTML", "RSS", "JSON" ]