name: GitHub Pages

on:
  push:
    branches:
      - main # Kích hoạt khi có commit mới vào nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Tải theme PaperMod
          fetch-depth: 0    # Lịch sử Git đầy đủ cho các bản phát hành

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Thư mục Hugo đã biên dịch
          publish_branch: gh-pages # Triển khai lên nhánh này